# Generated by Django 5.1.9 on 2025-05-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AuditID', models.CharField(editable=False, max_length=50, unique=True)),
                ('Module', models.CharField(choices=[('Loan', 'Loan'), ('Repayment', 'Repayment'), ('Disbursement', 'Disbursement')], max_length=50)),
                ('ActionPerformed', models.CharField(choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete')], max_length=10)),
                ('UserID', models.CharField(blank=True, max_length=150, null=True)),
                ('OldValue', models.JSONField(blank=True, null=True)),
                ('NewValue', models.JSONField(blank=True, null=True)),
                ('CreateBy', models.CharField(blank=True, max_length=50, null=True)),
                ('UpdateBy', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('LastUpdatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'AuditLogs',
            },
        ),
    ]
