# Generated by Django 5.1.9 on 2025-06-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuditTrail', '0003_auditlogs_ownerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogs',
            name='ActionPerformed',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10),
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='Module',
            field=models.CharField(choices=[('loan', 'Loan'), ('repayment', 'Repayment'), ('disbursement', 'Disbursement')], max_length=50),
        ),
    ]
