# Generated by Django 5.1.9 on 2025-06-24 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuditTrail', '0004_alter_auditlogs_actionperformed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlogs',
            name='AuditID',
        ),
    ]
