# Generated by Django 5.1.9 on 2025-05-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldKeyMapping',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'FieldKeyMapping',
                'unique_together': {('model_name', 'field_name')},
            },
        ),
    ]
