# Generated by Django 5.1.9 on 2025-05-26 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IpAddress', models.GenericIPAddressField()),
                ('Email', models.EmailField(max_length=254)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('LastUpdatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'loginLogs',
            },
        ),
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('OTP', models.CharField(max_length=6)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('IsVerified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'OTPRequest',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Username', models.CharField(max_length=255)),
                ('Role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='User', max_length=20)),
                ('IsActive', models.BooleanField(default=True)),
                ('IsStaff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'LoginUser',
            },
        ),
        migrations.CreateModel(
            name='ModuleTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModuleName', models.CharField(max_length=255)),
                ('CreateBy', models.CharField(blank=True, max_length=50, null=True)),
                ('UpdateBy', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('LastUpdatedAt', models.DateTimeField(auto_now=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ModuleTable',
            },
        ),
        migrations.CreateModel(
            name='ModuleLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IpAddress', models.GenericIPAddressField()),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ModuleLogs',
            },
        ),
    ]
