# Generated by Django 5.1.9 on 2025-06-22 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAuth', '0004_auditlog_modules_modulerole_permission_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalMatrix',
            fields=[
                ('matrix_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('matrix_name', models.CharField(max_length=50)),
                ('approval_on_submit', models.BooleanField(default=False)),
                ('levels', models.IntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginAuth.modules')),
            ],
            options={
                'db_table': 'approval_matrix',
            },
        ),
        migrations.CreateModel(
            name='Approvals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('approver_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('matrix_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginAuth.approvalmatrix')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginAuth.modules')),
            ],
            options={
                'db_table': 'approvals',
            },
        ),
        migrations.CreateModel(
            name='MatrixApprovers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('matrix_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='LoginAuth.approvalmatrix')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matrix_approvers',
            },
        ),
        migrations.AddIndex(
            model_name='approvalmatrix',
            index=models.Index(fields=['module', 'status'], name='approval_ma_module__0079d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalmatrix',
            constraint=models.CheckConstraint(condition=models.Q(('levels__gte', 1), ('levels__lte', 5)), name='levels_range'),
        ),
        migrations.AddIndex(
            model_name='approvals',
            index=models.Index(fields=['record_id', 'module'], name='approvals_record__7534d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvals',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1)), name='approval_level_positive'),
        ),
        migrations.AlterUniqueTogether(
            name='approvals',
            unique_together={('record_id', 'module', 'level')},
        ),
        migrations.AddIndex(
            model_name='matrixapprovers',
            index=models.Index(fields=['matrix_id'], name='matrix_appr_matrix__2dc8e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='matrixapprovers',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1)), name='level_positive'),
        ),
        migrations.AlterUniqueTogether(
            name='matrixapprovers',
            unique_together={('matrix_id', 'level')},
        ),
    ]
