# Generated by Django 5.1.9 on 2025-06-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAuth', '0005_approvalmatrix_approvals_matrixapprovers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalmatrix',
            name='matrix_name',
            field=models.CharField(max_length=100),
        ),
    ]
