# Generated by Django 5.1.9 on 2025-06-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAuth', '0006_alter_approvalmatrix_matrix_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalmatrix',
            name='matrix_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
