# Generated by Django 5.1.9 on 2025-06-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAuth', '0007_alter_approvalmatrix_matrix_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalmatrix',
            name='matrix_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
