# Generated by Django 5.1.9 on 2025-06-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAuth', '0009_alter_auditlog_action_alter_auditlog_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='createdByName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='updatedByName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
