# Generated by Django 5.1.9 on 2025-06-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAuth', '0010_modules_createdbyname_modules_updatedbyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='createdByName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='updatedByName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='createdByName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='updatedByName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
