# Generated by Django 5.1.9 on 2025-06-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAuth', '0011_permission_createdbyname_permission_updatedbyname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalmatrix',
            name='autoEscalation',
            field=models.IntegerField(blank=True, help_text='Number of times to auto escalate if pending', null=True),
        ),
        migrations.AddField(
            model_name='approvalmatrix',
            name='onRejection',
            field=models.CharField(choices=[('escalate', 'Escalate to next level'), ('terminate', 'Terminate workflow')], default='terminate', max_length=20),
        ),
    ]
