# Generated by Django 5.1.9 on 2025-06-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAuth', '0012_approvalmatrix_autoescalation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalmatrix',
            name='onRejection',
            field=models.CharField(choices=[('escalate', 'Escalate'), ('terminate', 'Terminate')], default='terminate', max_length=20),
        ),
    ]
