# Generated by Django 5.1.9 on 2025-06-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAuth', '0013_alter_approvalmatrix_onrejection'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalmatrix',
            name='autoEscalation_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Pending', max_length=20),
        ),
    ]
