# Generated by Django 5.1.9 on 2025-06-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAuth', '0014_approvalmatrix_autoescalation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvals',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
