# Generated by Django 5.1.9 on 2025-06-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAuth', '0015_alter_approvals_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', through='LoginAuth.UserRole', to='LoginAuth.role'),
        ),
    ]
