# Generated by Django 5.1.9 on 2025-06-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAuth', '0017_remove_user_roles_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalmatrix',
            name='createdByName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
