# Generated by Django 5.1.9 on 2025-06-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAuth', '0018_approvalmatrix_createdbyname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalmatrix',
            name='createdByName',
        ),
    ]
