# Generated by Django 5.1.9 on 2025-06-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAuth', '0019_remove_approvalmatrix_createdbyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrixapprovers',
            name='UserByName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='matrixapprovers',
            name='createdByName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
