# Generated by Django 5.1.9 on 2025-06-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAuth', '0020_matrixapprovers_userbyname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrixapprovers',
            name='createdByName',
        ),
    ]
