# Generated by Django 5.1.9 on 2025-05-26 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InquiryLoanProcess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionSetup',
            fields=[
                ('auction_id', models.AutoField(primary_key=True, serialize=False)),
                ('seizure_order_copy', models.FileField(upload_to='seizure_orders/')),
                ('auction_type', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Broker-Mediated', 'Broker-Mediated')], max_length=20)),
                ('reserve_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_url', models.URLField(blank=True, null=True)),
                ('asset_type', models.CharField(max_length=100)),
                ('valuation_report', models.FileField(upload_to='valuation_reports/')),
                ('asset_photos', models.ImageField(upload_to='asset_photos/')),
                ('insurance_policy', models.FileField(blank=True, null=True, upload_to='insurance_policies/')),
                ('bidder_pan_card', models.FileField(upload_to='bid_docs/')),
                ('bidder_aadhaar', models.FileField(upload_to='bid_docs/')),
                ('emd_receipt', models.FileField(upload_to='bid_docs/')),
                ('bid_declaration_form', models.FileField(upload_to='bid_docs/')),
                ('sale_deed', models.FileField(upload_to='post_auction/')),
                ('buyer_kyc_package', models.FileField(upload_to='post_auction/')),
                ('payment_proof', models.FileField(upload_to='post_auction/payment_proof/')),
                ('handover_report', models.FileField(upload_to='post_auction/handover_report/')),
                ('rbi_auction_report', models.FileField(upload_to='compliance/rbi_auction_report/')),
                ('audit_trail_log', models.FileField(upload_to='compliance/')),
                ('tds_certificate', models.FileField(blank=True, null=True, upload_to='compliance/tds_certificate/')),
                ('loan_id', models.ForeignKey(db_column='loan_id', on_delete=django.db.models.deletion.CASCADE, to='InquiryLoanProcess.loanapplication')),
            ],
            options={
                'db_table': 'AuctionSetup',
            },
        ),
    ]
