# Generated by Django 5.1.9 on 2025-05-30 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionsetup',
            old_name='asset_photos',
            new_name='AssetPhotos',
        ),
        migrations.RenameField(
            model_name='auctionsetup',
            old_name='asset_type',
            new_name='AssetType',
        ),
        migrations.RenameField(
            model_name='auctionsetup',
            old_name='auction_id',
            new_name='AuctionId',
        ),
        migrations.RenameField(
            model_name='auctionsetup',
            old_name='auction_type',
            new_name='AuctionType',
        ),
        migrations.RenameField(
            model_name='auctionsetup',
            old_name='audit_trail_log',
            new_name='AuditTrailLog',
        ),
        migrations.RenameField(
            model_name='auctionsetup',
            old_name='bid_declaration_form',
            new_name='BidDeclarationForm',
        ),
        migrations.RenameField(
            model_name='auctionsetup',
            old_name='bidder_aadhaar',
            new_name='BidderAadhaar',
        ),
        migrations.RenameField(
            model_name='auctionsetup',
            old_name='bidder_pan_card',
            new_name='BidderPanCard',
        ),
        migrations.RenameField(
            model_name='auctionsetup',
            old_name='buyer_kyc_package',
            new_name='BuyerKycPackage',
        ),
        migrations.RenameField(
            model_name='auctionsetup',
            old_name='emd_receipt',
            new_name='EMD_Receipt',
        ),
        migrations.RenameField(
            model_name='auctionsetup',
            old_name='handover_report',
            new_name='HandoverReport',
        ),
        migrations.RenameField(
            model_name='auctionsetup',
            old_name='insurance_policy',
            new_name='InsurancePolicy',
        ),
        migrations.RenameField(
            model_name='auctionsetup',
            old_name='loan_id',
            new_name='LoanId',
        ),
        migrations.RenameField(
            model_name='auctionsetup',
            old_name='payment_proof',
            new_name='PaymentProof',
        ),
        migrations.RenameField(
            model_name='auctionsetup',
            old_name='platform_url',
            new_name='PlatformUrl',
        ),
        migrations.RenameField(
            model_name='auctionsetup',
            old_name='rbi_auction_report',
            new_name='RBI_AuctionReport',
        ),
        migrations.RenameField(
            model_name='auctionsetup',
            old_name='reserve_price',
            new_name='ReservePrice',
        ),
        migrations.RenameField(
            model_name='auctionsetup',
            old_name='sale_deed',
            new_name='SaleDeed',
        ),
        migrations.RenameField(
            model_name='auctionsetup',
            old_name='seizure_order_copy',
            new_name='SeizureOrderCopy',
        ),
        migrations.RenameField(
            model_name='auctionsetup',
            old_name='tds_certificate',
            new_name='TDS_Certificate',
        ),
        migrations.RenameField(
            model_name='auctionsetup',
            old_name='valuation_report',
            new_name='ValuationReport',
        ),
    ]
