# Generated by Django 5.1.9 on 2025-06-04 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0002_rename_asset_photos_auctionsetup_assetphotos_and_more'),
        ('Masters', '0035_vehicle_branchid_vehicle_departmentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionsetup',
            name='BranchId',
            field=models.ForeignKey(db_column='BranchId', default=1, on_delete=django.db.models.deletion.CASCADE, to='Masters.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionsetup',
            name='DepartmentId',
            field=models.ForeignKey(db_column='DepartmentId', default=1, on_delete=django.db.models.deletion.CASCADE, to='Masters.department'),
            preserve_default=False,
        ),
    ]
