# Generated by Django 5.1.9 on 2025-06-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0004_auctionsetup_ownerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionsetup',
            name='AdditionalDocuments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
