# Generated by Django 5.1.9 on 2025-06-24 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0005_auctionsetup_additionaldocuments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionsetup',
            name='AdditionalDocuments',
        ),
        migrations.CreateModel(
            name='AdditionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='auction_documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Auction.auctionsetup')),
            ],
        ),
    ]
