# Generated by Django 5.1.9 on 2025-06-24 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0006_remove_auctionsetup_additionaldocuments_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalDocument',
        ),
    ]
