# Generated by Django 5.1.9 on 2025-06-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0007_delete_additionaldocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionsetup',
            name='AuctionType',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('broker-mediated', 'broker-mediated')], max_length=20),
        ),
    ]
