# Generated by Django 5.1.9 on 2025-06-27 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0009_auctionassetphoto_auctioncompliancedocument_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctioncompliancedocument',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='auctioninsurancepolicy',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='auctionvaluationreport',
            name='auction',
        ),
        migrations.DeleteModel(
            name='AuctionAssetPhoto',
        ),
        migrations.DeleteModel(
            name='AuctionComplianceDocument',
        ),
        migrations.DeleteModel(
            name='AuctionInsurancePolicy',
        ),
        migrations.DeleteModel(
            name='AuctionValuationReport',
        ),
    ]
