# Generated by Django 5.1.9 on 2025-05-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryLoanProcess', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newinquiry',
            old_name='Aadhaar_Number',
            new_name='AadhaarNumber',
        ),
        migrations.RenameField(
            model_name='newinquiry',
            old_name='Address_Line_1',
            new_name='AddressLine1',
        ),
        migrations.RenameField(
            model_name='newinquiry',
            old_name='Address_Line_2',
            new_name='AddressLine2',
        ),
        migrations.RenameField(
            model_name='newinquiry',
            old_name='Address_Type',
            new_name='AddressType',
        ),
        migrations.RenameField(
            model_name='newinquiry',
            old_name='Alternate_Phone_Number',
            new_name='AlternatePhoneNumber',
        ),
        migrations.RenameField(
            model_name='newinquiry',
            old_name='Date_of_Birth',
            new_name='DateOfBirth',
        ),
        migrations.RenameField(
            model_name='newinquiry',
            old_name='Duration_at_Address',
            new_name='DurationAtAddress',
        ),
        migrations.RenameField(
            model_name='newinquiry',
            old_name='Email_Address',
            new_name='EmailAddress',
        ),
        migrations.RenameField(
            model_name='newinquiry',
            old_name='Fathers_Mothers_Name',
            new_name='FathersMothersName',
        ),
        migrations.RenameField(
            model_name='newinquiry',
            old_name='First_Name',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='newinquiry',
            old_name='Follow_up_Notes',
            new_name='FollowUpNotes',
        ),
        migrations.RenameField(
            model_name='newinquiry',
            old_name='Inquiry_Status',
            new_name='InquiryStatus',
        ),
        migrations.RenameField(
            model_name='newinquiry',
            old_name='Last_Name',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='newinquiry',
            old_name='Loan_Amount_Requested',
            new_name='LoanAmountRequested',
        ),
        migrations.RenameField(
            model_name='newinquiry',
            old_name='Loan_Purpose',
            new_name='LoanPurpose',
        ),
        migrations.RenameField(
            model_name='newinquiry',
            old_name='Marital_Status',
            new_name='MaritalStatus',
        ),
        migrations.RenameField(
            model_name='newinquiry',
            old_name='Middle_Name',
            new_name='MiddleName',
        ),
        migrations.RenameField(
            model_name='newinquiry',
            old_name='PAN_Number',
            new_name='PANNumber',
        ),
        migrations.RenameField(
            model_name='newinquiry',
            old_name='Phone_Number',
            new_name='PhoneNumber',
        ),
    ]
