# Generated by Django 5.1.9 on 2025-06-05 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryLoanProcess', '0010_penalty_branchid_penalty_departmentid'),
        ('Masters', '0035_vehicle_branchid_vehicle_departmentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementinfo',
            name='BranchId',
            field=models.ForeignKey(db_column='BranchId', default=1, on_delete=django.db.models.deletion.CASCADE, to='Masters.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disbursementinfo',
            name='DepartmentId',
            field=models.ForeignKey(db_column='DepartmentId', default=2, on_delete=django.db.models.deletion.CASCADE, to='Masters.department'),
            preserve_default=False,
        ),
    ]
