# Generated by Django 5.1.9 on 2025-06-21 10:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryLoanProcess', '0019_foreclosure_ownerid'),
        ('Masters', '0053_country_currency_remove_branch_currencycode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='Frequency',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], default=1, max_length=20, verbose_name='Repayment Frequency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='LoanAmount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(1000.0)], verbose_name='Loan Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='ProductId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Masters.loanproductmaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='RateOfInterest',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Rate of Interest (%)'),
            preserve_default=False,
        ),
    ]
