# Generated by Django 5.1.9 on 2025-06-24 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryLoanProcess', '0020_loanapplication_frequency_loanapplication_loanamount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='ProductId',
        ),
    ]
