# Generated by Django 5.1.9 on 2025-06-24 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryLoanProcess', '0021_remove_loanapplication_productid'),
        ('Masters', '0053_country_currency_remove_branch_currencycode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='ProductId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Masters.loanproductmaster'),
            preserve_default=False,
        ),
    ]
