# Generated by Django 5.1.9 on 2025-06-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryLoanProcess', '0022_loanapplication_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalinfo',
            name='ApprovalStatus',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('hold', 'Hold')], default='Hold', max_length=10),
        ),
        migrations.AlterField(
            model_name='disbursementinfo',
            name='DisbursementMode',
            field=models.CharField(choices=[('neft', 'NEFT'), ('cheque', 'Cheque'), ('upi', 'UPI')], max_length=50),
        ),
        migrations.AlterField(
            model_name='disbursementinfo',
            name='DisbursementStatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='disbursementinfo',
            name='DisbursementType',
            field=models.CharField(choices=[('full', 'Full'), ('partial', 'Partial')], default='Full', max_length=20),
        ),
        migrations.AlterField(
            model_name='full_kyc',
            name='KYCStatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='AccountType',
            field=models.CharField(choices=[('saving', 'Saving'), ('current', 'Current')], max_length=7, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='EmploymentType',
            field=models.CharField(choices=[('salaried', 'salaried'), ('self-employed', 'Self-employed')], max_length=50, verbose_name='Employment Type'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='Frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20, verbose_name='Repayment Frequency'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='RepaymentMode',
            field=models.CharField(choices=[('ecs', 'ECS'), ('online', 'Online'), ('cash', 'Cash')], max_length=50, verbose_name='Repayment Mode'),
        ),
        migrations.AlterField(
            model_name='newinquiry',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='newinquiry',
            name='InquiryStatus',
            field=models.CharField(choices=[('open', 'Open'), ('converted', 'Converted'), ('dropped', 'Dropped')], default='Open', max_length=9, verbose_name='Inquiry Status'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='PenaltyStatus',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='Unpaid', max_length=20),
        ),
    ]
