# Generated by Django 5.1.9 on 2025-07-01 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryLoanProcess', '0023_alter_approvalinfo_approvalstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='InquiryId',
            field=models.ForeignKey(db_column='InquiryId', default=2, on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='InquiryLoanProcess.newinquiry'),
            preserve_default=False,
        ),
    ]
