# Generated by Django 5.1.9 on 2025-07-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryLoanProcess', '0024_loanapplication_inquiryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='full_kyc',
            name='Digilocker',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/digilocker/'),
        ),
        migrations.AddField(
            model_name='full_kyc',
            name='DrivingLicense',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/driving_license/'),
        ),
        migrations.AddField(
            model_name='full_kyc',
            name='ElectricityBill',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/electricity_bill/'),
        ),
        migrations.AddField(
            model_name='full_kyc',
            name='ITRCompliance',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/itr_compliance/'),
        ),
        migrations.AddField(
            model_name='full_kyc',
            name='ReportCibil',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/credit_report/'),
        ),
        migrations.AddField(
            model_name='full_kyc',
            name='VoterId',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/voter_id/'),
        ),
    ]
