# Generated by Django 5.1.9 on 2025-07-02 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryLoanProcess', '0025_full_kyc_digilocker_full_kyc_drivinglicense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisetup',
            name='LoanId',
            field=models.ForeignKey(db_column='loan_id', default=2, on_delete=django.db.models.deletion.CASCADE, to='InquiryLoanProcess.loanapplication'),
            preserve_default=False,
        ),
    ]
