# Generated by Django 5.1.9 on 2025-07-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryLoanProcess', '0026_emisetup_loanid'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='AddressLine1',
            field=models.CharField(default='AddressLine1', max_length=255, verbose_name='Address Line 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='AddressLine2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='AddressType',
            field=models.CharField(blank=True, max_length=50, verbose_name='Address Type'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='AlternatePhoneNumber',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Alternate Phone Number'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='City',
            field=models.CharField(default='City', max_length=100, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='Country',
            field=models.CharField(default='India', max_length=50, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='DateOfBirth',
            field=models.DateField(default='2000-01-01', verbose_name='Date of Birth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='DurationAtAddress',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration at Address'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='EmailAddress',
            field=models.EmailField(default='emailAddres', max_length=100, verbose_name='Email Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='FathersMothersName',
            field=models.CharField(default='fathername', max_length=100, verbose_name="Father's/Mother's Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='FirstName',
            field=models.CharField(default='firstname', max_length=50, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='female', max_length=6, verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='Landmark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Landmark'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='LastName',
            field=models.CharField(default='lastname', max_length=50, verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='MaritalStatus',
            field=models.CharField(blank=True, max_length=30, verbose_name='Marital Status'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='MiddleName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='PhoneNumber',
            field=models.CharField(default='7857851258', max_length=15, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='Pincode',
            field=models.CharField(default='789658', max_length=6, verbose_name='Pincode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='State',
            field=models.CharField(default='madhyapradesh', max_length=100, verbose_name='State'),
            preserve_default=False,
        ),
    ]
