# Generated by Django 5.1.9 on 2025-07-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryLoanProcess', '0027_loanapplication_addressline1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='DisbursementDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='DisbursementMode',
            field=models.CharField(blank=True, choices=[('NEFT', 'NEFT'), ('Cheque', 'Cheque'), ('UPI', 'UPI')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='DisbursementNotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='DisbursementStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='DisbursementType',
            field=models.CharField(blank=True, choices=[('Full', 'Full'), ('Partial', 'Partial')], max_length=10, null=True),
        ),
    ]
