# Generated by Django 5.1.9 on 2025-07-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryLoanProcess', '0028_loanapplication_disbursementdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='ApplicationStatus',
            field=models.CharField(choices=[('Draft', 'Draft'), ('KYC Pending', 'KYC Pending'), ('Waiting for Approval', 'Waiting for Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Hold', 'Hold'), ('Disbursement Pending', 'Disbursement Pending'), ('Disbursement Completed', 'Disbursement Completed'), ('Disbursement in Progress', 'Disbursement in Progress')], default='Draft', max_length=50),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='LoanStatus',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], default='Active', max_length=20),
        ),
    ]
