# Generated by Django 5.1.9 on 2025-07-07 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryLoanProcess', '0030_full_kyc_bankstatementstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='MoreAttachmentFile',
            field=models.FileField(blank=True, null=True, upload_to='loan_attachments/'),
        ),
        migrations.CreateModel(
            name='LoanApplicationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='loan_attachments/')),
                ('UploadedAt', models.DateTimeField(auto_now_add=True)),
                ('Loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='InquiryLoanProcess.loanapplication')),
            ],
        ),
    ]
