# Generated by Django 5.1.9 on 2025-07-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryLoanProcess', '0031_loanapplication_moreattachmentfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emisetup',
            name='CreateBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emisetup',
            name='EMI_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='emisetup',
            name='PaidEMIS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emisetup',
            name='RemainingEMIS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emisetup',
            name='StartDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emisetup',
            name='TotalTenure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emisetup',
            name='UpdateBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
