# Generated by Django 5.1.9 on 2025-05-26 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InquiryLoanProcess', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateBy', models.CharField(blank=True, max_length=50, null=True)),
                ('UpdateBy', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('LastUpdatedAt', models.DateTimeField(auto_now=True)),
                ('InquiryId', models.ForeignKey(db_column='Inquiry_id', on_delete=django.db.models.deletion.CASCADE, to='InquiryLoanProcess.newinquiry')),
                ('Users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Assign',
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('Type', models.CharField(choices=[('Call', 'Call'), ('Email', 'Email'), ('Visit', 'Visit'), ('Other', 'Other')], max_length=50)),
                ('Subject', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Assigned_to', models.CharField(blank=True, max_length=50, null=True)),
                ('Create_by', models.CharField(blank=True, max_length=50, null=True)),
                ('Update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Last_updated_at', models.DateTimeField(auto_now=True)),
                ('InquiryId', models.ForeignKey(db_column='Inquiry_id', on_delete=django.db.models.deletion.CASCADE, to='InquiryLoanProcess.newinquiry')),
            ],
            options={
                'db_table': 'FollowUp',
            },
        ),
        migrations.CreateModel(
            name='inquiryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Action', models.CharField(choices=[('Edit', 'Edit'), ('Delete', 'Delete'), ('Assign', 'Assign'), ('Add Follow-up', 'Add Follow-up'), ('Note', 'Note'), ('Special Note', 'Special Note'), ('Verification', 'Verification'), ('Checklist', 'Checklist')], max_length=50)),
                ('Create_by', models.CharField(blank=True, max_length=50, null=True)),
                ('Update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Last_updated_at', models.DateTimeField(auto_now=True)),
                ('InquiryId', models.ForeignKey(db_column='Inquiry_id', on_delete=django.db.models.deletion.CASCADE, to='InquiryLoanProcess.newinquiry')),
            ],
            options={
                'db_table': 'inquiryAction',
            },
        ),
        migrations.CreateModel(
            name='inquiryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('AssignedTo', models.CharField(max_length=50, null=True)),
                ('CreateBy', models.CharField(blank=True, max_length=50, null=True)),
                ('UpdateBy', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('LastUpdatedAt', models.DateTimeField(auto_now=True)),
                ('InquiryId', models.ForeignKey(db_column='Inquiry_id', on_delete=django.db.models.deletion.CASCADE, to='InquiryLoanProcess.newinquiry')),
            ],
            options={
                'db_table': 'inquiryNote',
            },
        ),
        migrations.CreateModel(
            name='SpecialNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('AssignedTo', models.CharField(max_length=50, null=True)),
                ('CreateBy', models.CharField(blank=True, max_length=50, null=True)),
                ('UpdateBy', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('LastUpdatedAt', models.DateTimeField(auto_now=True)),
                ('InquiryId', models.ForeignKey(db_column='Inquiry_id', on_delete=django.db.models.deletion.CASCADE, to='InquiryLoanProcess.newinquiry')),
            ],
            options={
                'db_table': 'SpecialNote',
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VerificationMode', models.CharField(choices=[('on_site', 'On site Visit'), ('online', 'Online')], max_length=20)),
                ('AssignTo', models.CharField(max_length=150)),
                ('Remark', models.TextField(blank=True, null=True)),
                ('VerificationStatus', models.CharField(choices=[('passed', 'Passed'), ('rejected', 'Rejected'), ('hold', 'Hold')], max_length=20)),
                ('VerificationDate', models.DateField(auto_now_add=True)),
                ('CreateBy', models.CharField(blank=True, max_length=50, null=True)),
                ('UpdateBy', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('LastUpdatedAt', models.DateTimeField(auto_now=True)),
                ('InquiryId', models.ForeignKey(db_column='Inquiry_id', on_delete=django.db.models.deletion.CASCADE, to='InquiryLoanProcess.newinquiry')),
            ],
            options={
                'db_table': 'Verification',
            },
        ),
    ]
