# Generated by Django 5.1.9 on 2025-05-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryAction', '0002_alter_followup_inquiryid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followup',
            old_name='Assigned_to',
            new_name='assigned_to',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='Create_by',
            new_name='create_by',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='Created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='InquiryId',
            new_name='inquiry_id',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='Last_updated_at',
            new_name='last_updated_at',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='Subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='Time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='Update_by',
            new_name='update_by',
        ),
    ]
