# Generated by Django 5.1.9 on 2025-05-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryAction', '0003_rename_assigned_to_followup_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='CreateBy',
            field=models.CharField(blank=True, db_column='CreateBy', max_length=50, null=True),
        ),
        migrations.RenameField(
            model_name='assign',
            old_name='CreateBy',
            new_name='create_by',
        ),
        migrations.AlterField(
            model_name='assign',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedAt'),
        ),
        migrations.RenameField(
            model_name='assign',
            old_name='CreatedAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='assign',
            old_name='InquiryId',
            new_name='inquiry_id',
        ),
        migrations.AlterField(
            model_name='assign',
            name='LastUpdatedAt',
            field=models.DateTimeField(auto_now=True, db_column='LastUpdatedAt'),
        ),
        migrations.RenameField(
            model_name='assign',
            old_name='LastUpdatedAt',
            new_name='last_updated_at',
        ),
        migrations.AlterField(
            model_name='assign',
            name='UpdateBy',
            field=models.CharField(blank=True, db_column='UpdateBy', max_length=50, null=True),
        ),
        migrations.RenameField(
            model_name='assign',
            old_name='UpdateBy',
            new_name='update_by',
        ),
        migrations.RenameField(
            model_name='assign',
            old_name='Users',
            new_name='users',
        ),
    ]
