# Generated by Django 5.1.9 on 2025-05-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryAction', '0005_alter_inquirynote_inquiryid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquirynote',
            old_name='AssignedTo',
            new_name='assigned_to',
        ),
        migrations.AlterField(
            model_name='inquirynote',
            name='CreateBy',
            field=models.CharField(blank=True, db_column='CreateBy', max_length=50, null=True),
        ),
        migrations.RenameField(
            model_name='inquirynote',
            old_name='CreateBy',
            new_name='create_by',
        ),
        migrations.AlterField(
            model_name='inquirynote',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedAt'),
        ),
        migrations.RenameField(
            model_name='inquirynote',
            old_name='CreatedAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='inquirynote',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='inquirynote',
            old_name='InquiryId',
            new_name='inquiry_id',
        ),
        migrations.AlterField(
            model_name='inquirynote',
            name='LastUpdatedAt',
            field=models.DateTimeField(auto_now=True, db_column='LastUpdatedAt'),
        ),
        migrations.RenameField(
            model_name='inquirynote',
            old_name='LastUpdatedAt',
            new_name='last_updated_at',
        ),
        migrations.AlterField(
            model_name='inquirynote',
            name='UpdateBy',
            field=models.CharField(blank=True, db_column='UpdateBy', max_length=50, null=True),
        ),
        migrations.RenameField(
            model_name='inquirynote',
            old_name='UpdateBy',
            new_name='update_by',
        ),
    ]
