# Generated by Django 5.1.9 on 2025-05-27 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryAction', '0006_rename_assignedto_inquirynote_assigned_to_and_more'),
        ('InquiryLoanProcess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='InquiryId',
            field=models.ForeignKey(db_column='InquiryId', on_delete=django.db.models.deletion.CASCADE, to='InquiryLoanProcess.newinquiry'),
        ),
    ]
