# Generated by Django 5.1.9 on 2025-05-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryAction', '0007_alter_verification_inquiryid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followup',
            old_name='assigned_to',
            new_name='AssignedTo',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='create_by',
            new_name='CreateBy',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='created_at',
            new_name='CreatedAt',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='inquiry_id',
            new_name='InquiryId',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='last_updated_at',
            new_name='LastUpdatedAt',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='subject',
            new_name='Subject',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='time',
            new_name='Time',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='type',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='update_by',
            new_name='UpdateBy',
        ),
        migrations.RenameField(
            model_name='inquiryaction',
            old_name='Create_by',
            new_name='CreateBy',
        ),
        migrations.RenameField(
            model_name='inquiryaction',
            old_name='Created_at',
            new_name='CreatedAt',
        ),
        migrations.RenameField(
            model_name='inquiryaction',
            old_name='Last_updated_at',
            new_name='LastUpdatedAt',
        ),
        migrations.RenameField(
            model_name='inquiryaction',
            old_name='Update_by',
            new_name='UpdateBy',
        ),
    ]
