# Generated by Django 5.1.9 on 2025-05-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryAction', '0008_rename_assigned_to_followup_assignedto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assign',
            old_name='create_by',
            new_name='CreateBy',
        ),
        migrations.RenameField(
            model_name='assign',
            old_name='created_at',
            new_name='CreatedAt',
        ),
        migrations.RenameField(
            model_name='assign',
            old_name='inquiry_id',
            new_name='InquiryId',
        ),
        migrations.RenameField(
            model_name='assign',
            old_name='last_updated_at',
            new_name='LastUpdatedAt',
        ),
        migrations.RenameField(
            model_name='assign',
            old_name='update_by',
            new_name='UpdateBy',
        ),
        migrations.RenameField(
            model_name='assign',
            old_name='users',
            new_name='Users',
        ),
        migrations.RenameField(
            model_name='inquirynote',
            old_name='assigned_to',
            new_name='AssignedTo',
        ),
        migrations.RenameField(
            model_name='inquirynote',
            old_name='create_by',
            new_name='CreateBy',
        ),
        migrations.RenameField(
            model_name='inquirynote',
            old_name='created_at',
            new_name='CreatedAt',
        ),
        migrations.RenameField(
            model_name='inquirynote',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='inquirynote',
            old_name='inquiry_id',
            new_name='InquiryId',
        ),
        migrations.RenameField(
            model_name='inquirynote',
            old_name='last_updated_at',
            new_name='LastUpdatedAt',
        ),
        migrations.RenameField(
            model_name='inquirynote',
            old_name='update_by',
            new_name='UpdateBy',
        ),
    ]
