# Generated by Django 5.1.9 on 2025-06-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryAction', '0011_inquiryaction_branchid_inquiryaction_departmentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiryaction',
            name='BranchId',
        ),
        migrations.RemoveField(
            model_name='inquiryaction',
            name='DepartmentId',
        ),
    ]
