# Generated by Django 5.1.9 on 2025-06-13 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryAction', '0015_followup_ownerid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='OwnerId',
            field=models.ForeignKey(db_column='OwnerId', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiryaction',
            name='OwnerId',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assign',
            name='Users',
            field=models.ManyToManyField(related_name='assigned_inquiries', to=settings.AUTH_USER_MODEL),
        ),
    ]
