# Generated by Django 5.1.9 on 2025-06-13 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryAction', '0016_assign_ownerid_inquiryaction_ownerid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assign',
            name='OwnerId',
        ),
        migrations.AlterField(
            model_name='assign',
            name='Users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
