# Generated by Django 5.1.9 on 2025-06-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryAction', '0020_verification_ownerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='Type',
            field=models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('visit', 'Visit'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inquiryaction',
            name='Action',
            field=models.CharField(choices=[('edit', 'Edit'), ('delete', 'Delete'), ('assign', 'Assign'), ('add follow-up', 'Add Follow-up'), ('note', 'Note'), ('special note', 'Special Note'), ('verification', 'Verification'), ('checklist', 'Checklist')], max_length=50),
        ),
    ]
