# Generated by Django 5.1.9 on 2025-07-02 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryAction', '0021_alter_followup_type_alter_inquiryaction_action'),
        ('InquiryLoanProcess', '0025_full_kyc_digilocker_full_kyc_drivinglicense_and_more'),
        ('Masters', '0075_customer_inquiryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='CustomerId',
            field=models.ForeignKey(db_column='Customer_Id', default=2, on_delete=django.db.models.deletion.CASCADE, related_name='followUp_id', to='Masters.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followup',
            name='LoanId',
            field=models.ForeignKey(db_column='loan_id', default=2, on_delete=django.db.models.deletion.CASCADE, to='InquiryLoanProcess.loanapplication'),
            preserve_default=False,
        ),
    ]
