# Generated by Django 5.1.9 on 2025-07-03 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryAction', '0022_followup_customerid_followup_loanid'),
        ('InquiryLoanProcess', '0026_emisetup_loanid'),
        ('Masters', '0075_customer_inquiryid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('CustomerId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.customer')),
                ('InquiryId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InquiryLoanProcess.newinquiry')),
                ('LoanId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InquiryLoanProcess.loanapplication')),
            ],
            options={
                'db_table': 'document_uploads',
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='InquiryAction.documentupload')),
            ],
            options={
                'db_table': 'document_files',
            },
        ),
    ]
