# Generated by Django 5.1.9 on 2025-07-03 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryAction', '0023_documentupload_documentfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentupload',
            name='description',
        ),
        migrations.RemoveField(
            model_name='documentupload',
            name='title',
        ),
    ]
