# Generated by Django 5.1.9 on 2025-07-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryAction', '0024_remove_documentupload_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='Worker',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
