"""
Django settings for ci_loan project.

Generated by 'django-admin startproject' using Django 5.1.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from datetime import timedelta
from pathlib import Path

import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j1u1q-xwym_09kzzu=q58hmy3&=2y3qp3%82(be@7^nm8(4@ei'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
APPEND_SLASH=False

ALLOWED_HOSTS = ['api.9orbits.com','localhost','74.225.250.89','127.0.0.1']
CORS_ALLOW_ALL_ORIGINS = True

AUTH_USER_MODEL = 'LoginAuth.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'ci_loan.Masters.apps.JobsConfig',
    # 'django_apscheduler',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'LoginAuth',  
    'Masters',
    'CompanyProfile',
    'UserManagement',
    'InquiryLoanProcess',
    'DisSetSystem',
    'InquiryAction',
    'AuditTrail',
    'CustomSettings',
    'Auction',
    'KycVerification',
    'FieldMapping',
    'CiLoanCore',
    
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,  # You can change this value as needed
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django.middleware.common.CommonMiddleware",
]

ROOT_URLCONF = 'ci_loan.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ci_loan.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'ci_loan_management',
        'USER': 'postgres',
        'PASSWORD': '3003',
        'HOST': 'localhost',
        'PORT': '5432'
    }
}


# Generate a key once using Fernet.generate_key()
ENCRYPTION_KEY = b'e4k75h52-4u0B2-5112Hr3JAszpLN0EDZfo5VYRlzS8='  # Store securely


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



#------ Configure Django Email Settings ----------- 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Use your email service provider's SMTP server
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'info@9orbits.com'#'Officielcrm@gmail.com'
EMAIL_HOST_PASSWORD = 'lmmmxntrpwglbdrh'#'zius iwaw hyeg bqvv'
DEFAULT_FROM_EMAIL = 'info@9orbits.com'  # This will be the "From" email address





# KYC Verification Settings
SUREPASS_CONFIG = {
    'CUSTOMER_ID': "your_customer_id_here",
    'BASE_URL': "https://sandbox.surepass.io/api/v1",
    'TOKEN': "your_default_token_here",
    'ENDPOINTS': {
        'aadhaar_generate_otp': "aadhaar-v2/generate-otp",
        'aadhaar_verify_otp': "aadhaar-v2/submit-otp",
        'pan_verification': "pan/pan",
        'dl_verification': "driving-license/driving-license",
        'voter_verification': "voter-id/voter-id",
        'bank_verification': "bank-verification/",
        'cibil_verification': "credit-report-cibil/fetch-report",
        'cibil_pdf': "credit-report-cibil/fetch-report-pdf",
        'electricity_verification': "utility/electricity/",
    }
}