# Generated by Django 5.1.9 on 2025-05-29 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LoginAuth', '0003_rename_createdat_loginlogs_createdat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UDF_ID', models.CharField(max_length=100)),
                ('FieldLabelName', models.CharField(max_length=255)),
                ('IsMandatory', models.BooleanField(default=False)),
                ('Type', models.CharField(choices=[('dropdown', 'Dropdown'), ('checkbox', 'Checkbox'), ('input_text', 'Input Text'), ('text_area', 'Text Area'), ('radio_button', 'Radio Button'), ('date', 'Date'), ('enum', 'Enum'), ('time', 'Time'), ('file_upload', 'File Upload'), ('img_upload', 'Img Upload'), ('video_upload', 'Video Upload')], max_length=50)),
                ('IsVisible', models.BooleanField(default=True)),
                ('CreateBy', models.CharField(blank=True, max_length=50, null=True)),
                ('UpdateBy', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('LastUpdatedAt', models.DateTimeField(auto_now=True)),
                ('ModuleId', models.ForeignKey(db_column='module_id', on_delete=django.db.models.deletion.CASCADE, to='LoginAuth.moduletable')),
            ],
            options={
                'db_table': 'custom_setting',
                'unique_together': {('ModuleId', 'UDF_ID', 'FieldLabelName')},
            },
        ),
    ]
