# Generated by Django 5.1.9 on 2025-07-02 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomSettings', '0003_customsetting_ownerid'),
        ('LoginAuth', '0021_remove_matrixapprovers_createdbyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsetting',
            name='ModuleId',
            field=models.ForeignKey(db_column='moduleId', on_delete=django.db.models.deletion.CASCADE, to='LoginAuth.moduletable'),
        ),
    ]
