# Generated by Django 5.1.9 on 2025-06-11 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyProfile', '0001_initial'),
        ('Masters', '0038_loanproductmaster_branchid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=255)),
                ('AddressLine1', models.CharField(max_length=255)),
                ('AddressLine2', models.CharField(blank=True, max_length=255, null=True)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('countryCode', models.CharField(max_length=10)),
                ('MobileNumber', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='companyProfile/logo/')),
                ('UserProfileImage', models.ImageField(blank=True, null=True, upload_to='company/profile/')),
                ('TermsAndConditions', models.TextField(blank=True, null=True)),
                ('CurrentPassword', models.CharField(blank=True, max_length=128, null=True)),
                ('NewPassword', models.CharField(blank=True, max_length=128, null=True)),
                ('ConfirmPassword', models.CharField(blank=True, max_length=128, null=True)),
                ('CreatedBy', models.CharField(max_length=150)),
                ('UpdatedBy', models.CharField(blank=True, max_length=150, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('BranchId', models.ForeignKey(db_column='BranchId', on_delete=django.db.models.deletion.CASCADE, to='Masters.branch')),
                ('DepartmentId', models.ForeignKey(db_column='DepartmentId', on_delete=django.db.models.deletion.CASCADE, to='Masters.department')),
            ],
            options={
                'db_table': 'CompanyProfile',
            },
        ),
    ]
