# Generated by Django 5.1.9 on 2025-06-19 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyProfile', '0003_companyprofile_ownerid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileSettings',
        ),
    ]
