# Generated by Django 5.1.9 on 2025-06-21 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyProfile', '0004_delete_profilesettings'),
        ('Masters', '0053_country_currency_remove_branch_currencycode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='CountryId',
            field=models.ForeignKey(db_column='CountryId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Masters.country'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='CurrencyId',
            field=models.ForeignKey(db_column='CurrencyId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Masters.currency'),
        ),
    ]
