# Generated by Django 5.1.9 on 2025-06-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyProfile', '0005_companyprofile_countryid_companyprofile_currencyid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='countryCode',
        ),
    ]
