# Generated by Django 5.1.9 on 2025-06-24 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyProfile', '0006_remove_companyprofile_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='CreatedBy',
        ),
    ]
