# Generated by Django 5.1.9 on 2025-05-26 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=150, unique=True)),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('MobileNumber', models.CharField(max_length=15, unique=True)),
                ('Role', models.CharField(max_length=100)),
                ('ReportingManager', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=255)),
                ('CreateBy', models.CharField(max_length=50)),
                ('UpdateBy', models.CharField(max_length=50)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('LastUpdatedAt', models.DateTimeField(auto_now=True)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Blocked', 'Blocked')], default='Active', max_length=10)),
                ('Branch', models.ForeignKey(db_column='BranchId', on_delete=django.db.models.deletion.CASCADE, to='Masters.branch')),
                ('Department', models.ForeignKey(db_column='DepartmentId', on_delete=django.db.models.deletion.CASCADE, to='Masters.department')),
                ('Designation', models.ForeignKey(db_column='DesignationId', on_delete=django.db.models.deletion.CASCADE, to='Masters.designation')),
            ],
            options={
                'db_table': 'UserManagement',
            },
        ),
    ]
